---
# Namespace (optional, aber empfohlen)
apiVersion: v1
kind: Namespace
metadata:
  name: ai-architect

---
# ConfigMap für Konfiguration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-architect-config
  namespace: ai-architect
data:
  OLLAMA_BASE_URL: "http://host.docker.internal:11434"
  OLLAMA_MODEL_NAME: "codellama:7b"
  OLLAMA_TEMPERATURE: "0.9"
  OLLAMA_MAX_MESSAGES: "10"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  INFO_APP_NAME: "ai-architect"
  INFO_APP_DESCRIPTION: "Artificial Intelligenz Application for Softwarearchitects"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "info,health"
  MANAGEMENT_INFO_ENV_ENABLED: "true"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-architect
  namespace: ai-architect
  labels:
    app: ai-architect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-architect
  template:
    metadata:
      labels:
        app: ai-architect
      annotations:
        kubernetes.io/change-cause: "Initial Deplyoment"
    spec:
      containers:
        - name: ai-architect
          image: ai-architect:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: ai-architect-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ai-architect-service
  namespace: ai-architect
  labels:
    app: ai-architect
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: ai-architect